name: Lint GitHub Actions
on:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"
      - "**/action.yml"
      - "**/action.yaml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  actionlint:
    name: actionlint
    permissions:
      contents: read # Required to checkout the repository
      security-events: write # add zizmor security events
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      ACTIONLINT_VERSION: 03d0035246f3e81f36aed592ffb4bebf33a03106 # v1.7.7
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Check workflow files
        run: |
          set -euo pipefail

          bash <(curl "https://raw.githubusercontent.com/rhysd/actionlint/${ACTIONLINT_VERSION}/scripts/download-actionlint.bash")
          ./actionlint -format "$(cat .github/workflows/actionlint-format.txt)" | tee results.sarif
        shell: bash

      - name: Upload to GitHub security events
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        with:
          sarif_file: results.sarif
          category: actionlint

  zizmor:
    name: zizmor
    permissions:
      contents: read # Required to checkout the repository
      security-events: write # add zizmor security events
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0
        with:
          persona: pedantic

  summary:
    name: summary
    if: always()
    needs: [actionlint, zizmor]
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          set -euo pipefail

          cat <<EOF>> "${GITHUB_STEP_SUMMARY}"
          ## Linting Results
          | Tool | Status |
          |------|--------|
          | actionlint | "${NEEDS_ACTIONLINT_RESULT}" |
          | zizmor | "${NEEDS_ZIZMOR_RESULT}" |

          EOF

        env:
          NEEDS_ACTIONLINT_RESULT: ${{ needs.actionlint.result }}
          NEEDS_ZIZMOR_RESULT: ${{ needs.zizmor.result }}
